plugins {
    id "com.android.application"
}

android {
    namespace "com.tool48.tgwabridge"
    compileSdk 35

    defaultConfig {
        applicationId "com.tool48.tgwabridge"
        minSdk 24
        targetSdk 35
        versionCode 16
        versionName "1.6.0"
        buildConfigField(
            "String",
            "CONTENT_PROVIDER_AUTHORITY",
            "\"com.tool48.tgwabridge.stickercontentprovider\""
        )
    }

    buildFeatures {
        buildConfig true
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }

    buildTypes {
        release {
            minifyEnabled false
            signingConfig signingConfigs.debug
        }
    }
}

dependencies {
    testImplementation "junit:junit:4.13.2"
}
